In [1]:
import pandas as pd

In [25]:
p = '/home/local/USHERBROOKE/owup2301/Téléchargements/all_six_datasets/all_six_datasets/weather'
df = pd.read_csv(f'{p}/weather.csv', index_col=0)

In [26]:
df.shape

(52696, 21)

In [27]:
df.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),...,wv (m/s),max. wv (m/s),wd (deg),rain (mm),raining (s),SWDR (W/m�),PAR (�mol/m�/s),max. PAR (�mol/m�/s),Tlog (degC),OT
date,,,,,,,,,,,,,,,,,,,,,
2020-01-01 00:10:00,1008.89,0.71,273.18,-1.33,86.1,6.43,5.54,0.89,3.42,5.49,...,1.02,1.60,224.3,0.0,0.0,0.0,0.0,0.0,11.45,428.1
2020-01-01 00:20:00,1008.76,0.75,273.22,-1.44,85.2,6.45,5.49,0.95,3.39,5.45,...,0.43,0.84,206.8,0.0,0.0,0.0,0.0,0.0,11.51,428.0
2020-01-01 00:30:00,1008.66,0.73,273.21,-1.48,85.1,6.44,5.48,0.96,3.39,5.43,...,0.61,1.48,197.1,0.0,0.0,0.0,0.0,0.0,11.60,427.6
2020-01-01 00:40:00,1008.64,0.37,272.86,-1.64,86.3,6.27,5.41,0.86,3.35,5.37,...,1.11,1.48,206.4,0.0,0.0,0.0,0.0,0.0,11.70,430.0
2020-01-01 00:50:00,1008.61,0.33,272.82,-1.50,87.4,6.26,5.47,0.79,3.38,5.42,...,0.49,1.40,209.6,0.0,0.0,0.0,0.0,0.0,11.81,432.2

In [28]:
df['OT']

date
2020-01-01 00:10:00    428.1
2020-01-01 00:20:00    428.0
2020-01-01 00:30:00    427.6
2020-01-01 00:40:00    430.0
2020-01-01 00:50:00    432.2
                       ...
2020-12-31 23:20:00    433.0
2020-12-31 23:30:00    439.6
2020-12-31 23:40:00    435.2
2020-12-31 23:50:00    433.9
2021-01-01 00:00:00    436.5
Name: OT, Length: 52696, dtype: float64